# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "sulav-api-terraform-state-bucket"
    dynamodb_table = "sulav-terraform-api-lock-table"
    encrypt        = true
    key            = "backend_api/terraform.tfstate"
    region         = "us-east-1"
  }
}
