# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
}


provider "aws" {
  region                   = "us-east-1"
  shared_credentials_file = "~/.aws/credentials"

  default_tags {
    tags = {
      Name = "sulav"
      Creator   = "sulav.adk.7@gmailcom"
      Project   = "Intern"
      Deletable = "Yes"
    }
  }

}
